muncie-events-mailhog:
  image: mailhog/mailhog:latest
  container_name: muncie-events-mailhog
  ports:
    - "8125:8025"

muncie-events-mysql:
  image: mysql:5.7
  container_name: muncie-events-mysql
  volumes:
      - ./tmp/data/mysql_db:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
  ports:
    - "8106:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}

muncie-events-apache:
  image: webdevops/php-apache-dev:7.4
  container_name: muncie-events-apache
  volumes:
    - ./:/var/www/app
  ports:
    - "8180:80"
  links:
    - muncie-events-php-fpm

muncie-events-php-fpm:
  build: .
  dockerfile: ./docker/php-fpm/Dockerfile
  container_name: muncie-events-php-fpm
  volumes:
    - ../:/var/www/muncie-events
    - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.4/fpm/conf.d/99-overrides.ini
  links:
    - muncie-events-mailhog
    - muncie-events-mysql
