version: "3.9"
services:
  web:
    build:
      context: ..
      dockerfile: webserver.Dockerfile
    container_name: muncie-events-webserver
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    environment:
      - APP_NAME="muncie_events_api"
      - DEBUG=true
      - SECURITY_SALT="u42Me9mo3ZcM3jv34WCYxKpJDG7MGuzAiGEhUs3p"
      - FULL_BASE_URL=null
      - COOKIE_KEY="UtTnd4V2HFEnueCXr6PeRTfbf2R6CZyBr0SQJ0BTQLs"
      - PASSWORD_RESET_SALT="tA4mdDu6CHD7mGXpV5WD"
      - AUTOMAILER_PASSWORD="y0cxzgQeH5"
      - CATEGORY_ICON_BASE_URL="https://muncieevents.localhost/img/icons/categories/"
      - EVENT_IMG_BASE_URL="https://muncieevents.localhost/img/events/"
      - EVENT_IMG_PATH="C:\\xampp\\htdocs\\muncie_events\\app\\webroot\\img\\events"
      - SLACK_WEBHOOK="https://hooks.slack.com/services/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"
      - PHP_IDE_CONFIG=serverName=Docker

      # Database
      - DB_DATABASE="okbvtfr_muncieevents"
      - DB_USERNAME="root"
      - DB_PASSWORD=""

      # Services
      - RECAPTCHA_SITE_KEY="6LeDpjoUAAAAADAE8vX2DOVuuRYQSmSqRhvxIr5G"
      - RECAPTCHA_SECRET="6LeDpjoUAAAAADGXOqytNX_LkCz4o9cYNhtQJpZ3"
  db:
    image: mysql:5.7
    container_name: muncie-events-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: okbvtfr_muncieevents
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_user_pass
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - ./tmp/data/mysql_db:/var/lib/mysql
